version: "3"

services:
  payment:
    container_name: payment
    build:
      dockerfile: ./docker/Dockerfile
      context: ./payment
    ports:
      - 8000:8000
    command: start_server
    env_file:
      - ./payment/docker/.env
    depends_on:
      - postgres
      - kafka

  consumer:
    container_name: consumer
    build:
      dockerfile: ./docker/Dockerfile
      context: ./payment
    command: start_consumer
    env_file:
      - ./payment/docker/.env
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:13-alpine
    container_name: payment_postgres
    ports:
      - 5435:5432
    restart: always
    volumes:
      - payment_pg:/var/lib/postgresql/data
    env_file:
      - ./payment/docker/.env

#  zookeeper:
#    image: bitnami/zookeeper:latest
#    ports:
#      - 2181:2181
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    volumes:
#      - payment_zookeeper_data:/var/lib/zookeeper/data
#      - payment_zookeeper_log:/var/lib/zookeeper/log
#
#  kafka:
#    image: bitnami/kafka:latest
#    ports:
#      - 9092:9092
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - payment_kafka:/bitnami/kafka
#    depends_on:
#      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    volumes:
      - 'payment_zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    volumes:
      - 'payment_kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


volumes:
  payment_pg:
  payment_kafka_data:
  payment_zookeeper_data:
#  payment_zookeeper_log:
